name: web-test-build

on:
    push:
    # pull_request:
    #     types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:18-bookworm
                env:
                    POSTGRES_USER: hackyeah2026
                    POSTGRES_PASSWORD: hackyeah2026
                    POSTGRES_DB: hackyeah2026
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd="pg_isready -U hackyeah2026 -d hackyeah2026"
                    --health-interval=5s
                    --health-timeout=5s
                    --health-retries=10

        defaults:
            run:
                working-directory: web

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: pnpm
                  cache-dependency-path: web/pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm run build
              env:
                  DATABASE_URL: postgresql://hackyeah2026:hackyeah2026@localhost:5432/hackyeah2026
                  PAYLOAD_SECRET: hackyeah2026-payload-secret